//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDHack2019Entities : DbContext
    {
        public BDHack2019Entities()
            : base("name=BDHack2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCampaign> TblCampaign { get; set; }
        public virtual DbSet<TblUser> TblUser { get; set; }
    
        public virtual int SP_CreateCampaign(Nullable<int> pCam_Name, string pCam_language, string pCam_Location, string pcam_ContactsList)
        {
            var pCam_NameParameter = pCam_Name.HasValue ?
                new ObjectParameter("pCam_Name", pCam_Name) :
                new ObjectParameter("pCam_Name", typeof(int));
    
            var pCam_languageParameter = pCam_language != null ?
                new ObjectParameter("pCam_language", pCam_language) :
                new ObjectParameter("pCam_language", typeof(string));
    
            var pCam_LocationParameter = pCam_Location != null ?
                new ObjectParameter("PCam_Location", pCam_Location) :
                new ObjectParameter("PCam_Location", typeof(string));
    
            var pcam_ContactsListParameter = pcam_ContactsList != null ?
                new ObjectParameter("Pcam_ContactsList", pcam_ContactsList) :
                new ObjectParameter("Pcam_ContactsList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateCampaign", pCam_NameParameter, pCam_languageParameter, pCam_LocationParameter, pcam_ContactsListParameter);
        }
    
        public virtual ObjectResult<SP_ListCampaign_Result> SP_ListCampaign()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListCampaign_Result>("SP_ListCampaign");
        }
    }
}
