//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public int IdUser { get; set; }
        public string User_First_Name { get; set; }
        public string User_Last_Name { get; set; }
        public string User_Password { get; set; }
        public string User_Nationality { get; set; }
        public Nullable<System.DateTime> User_BirthDate { get; set; }
        public string User_Addictions { get; set; }
        public string User_Diseases { get; set; }
        public string User_Ethnicity { get; set; }
        public Nullable<int> User_Sons { get; set; }
        public string User_EducationLevel { get; set; }
        public string User_Gender { get; set; }
        public string User_Icome { get; set; }
        public string User_Religion { get; set; }
        public string User_Location { get; set; }
    }
}
